theme: jekyll-theme-minimal

title: "CaféTAL"
description: "Reading Group ATILF, Université de Lorraine, Nancy, France"
logo: assets/img/ATILF_logo.jpg
author:
  name: Aman Sinha
  url:  https://atilf-reading-group.com

organizers:
  - Aman Sinha
  - Hee-Soo Choi
  - Mathieu Constant

github: false
